//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcprojee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dersler
    {
        public int dersid { get; set; }
        public string dersadi { get; set; }
        public string ogretmen { get; set; }
        public string derssaati { get; set; }
    }
}
